import 'dart:ui';

import 'package:Cekos/models/koseekerModelSingle.dart';
import 'package:Cekos/services/koseekerViewModel.dart';
import 'package:Cekos/services/services.dart';
import 'package:Cekos/ui/widgets/widgets.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flushbar/flushbar.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:flutter_signin_button/flutter_signin_button.dart';
import 'package:mapbox_gl/mapbox_gl.dart';
import 'package:modal_bottom_sheet/modal_bottom_sheet.dart';
import 'package:salomon_bottom_bar/salomon_bottom_bar.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:syncfusion_flutter_datepicker/datepicker.dart';
import 'package:intl/intl.dart';
import 'package:touchable_opacity/touchable_opacity.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:webview_flutter/webview_flutter.dart';
import 'dart:async';
import 'package:Cekos/ui/widgets/custom_expantion_tile.dart' as custom;
import 'package:http/http.dart' as http;

part 'signin_page.dart';
part 'main_page.dart';
part 'perluaswawasan_webview.dart';
part 'buttonnavigationbarpage.dart';
part 'explorepage.dart';
part 'profilepage.dart';
part 'propertidetailpage.dart';
part 'searchcontrolpage.dart';
part 'survey.dart';
part 'booking.dart';
part 'lokasi.dart';
part 'favorite.dart';
part 'bookingTab.dart';
part 'likesTab.dart';
part 'surveyTab.dart';
part 'webviewDetail.dart';
part 'pembayaran.dart';
